name: elliptical_progress_bar
description: A flutter package to create elliptical progress bar.
version: 0.0.1+1
homepage: https://github.com/A7ALABS/elliptical-progress-bar
issue_tracker: https://github.com/A7ALABS/elliptical-progress-bar/issues

platforms:
  android:
  ios:

topics:
  - progress-bar
  - progress-indicator
  - elliptical-progress-bar
  - ellipse

screenshots:
  - description: 'This screenshot shows the progress bar with different customisations (Android).'
    path: example/screenshots/android.png
  - description: 'This screenshot shows the progress bar with different customisations (iOS).'
    path: example/screenshots/ios.png

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: